-- Databricks notebook source
SELECT MNEMO_LIGNE,SENS_PARCOURS,NO_CHAINAGE,MNEMO_ORIG, min(ORDRE_POINT) AS ordre
FROM saebus.V_REF_TOPO_CHAINAGE_BUS
where
ORDRE_POINT =1
GROUP BY 
MNEMO_LIGNE,SENS_PARCOURS,NO_CHAINAGE,MNEMO_ORIG
UNION 
SELECT distinct
MNEMO_LIGNE,SENS_PARCOURS,NO_CHAINAGE,MNEMO_ORIG, ORDRE_POINT AS ordre
FROM  saebus.V_REF_TOPO_CHAINAGE_BUS
 where 
ORDRE_POINT =NB_POINTS_TOPO_CHAINAGE 
